version: '3'

services:
  gwcloud_react_host_static:
    build:
      dockerfile: ./docker/gwcloud_react_host_static.Dockerfile
      context: .
    image: nexus.gwdc.org.au/gwcloud-dev/gwcloud_react_host_static:0.8
    container_name: gwcloud_react_host_static
    ports:
      - "80"
