---
# Ingress - Configuration documentation: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: gwcloud-org-au-ing
  namespace: gwcloud
spec:
  host: gwcloud.org.au
  upstreams:
    - name: gwcloud-auth
      service: gwcloud-auth
      port: 8000
    - name: gwcloud-react-host
      service: gwcloud-react-host
      port: 8000
    - name: gwcloud-job-server-http
      service: gwcloud-job-server
      port: 8000
    - name: gwcloud-job-server-websocket
      service: gwcloud-job-server
      port: 8001
    - name: gwcloud-bilby
      service: gwcloud-bilby-nginx
      port: 8000
  routes:
    - path: ~* ^(/auth/ligo/|/Shibboleth.sso.*)
      action:
        redirect:
          url: https://gw-cloud.org${request_uri}
          code: 302
    - path: ~* ^(/auth/static/.*|/auth/graphql)
      action:
        pass: gwcloud-auth
    - path: ~* ^(/bilby/static/.*|/bilby/graphql)
      action:
        pass: gwcloud-bilby
    - path: ~* ^(/job/ws.*)
      action:
        pass: gwcloud-job-server-websocket
    - path: ~* ^(/job/.*)
      action:
        pass: gwcloud-job-server-http
    - path: / 
      action:
        pass: gwcloud-react-host 
---
