---
# 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwcloud-react-host
  namespace: gwcloud
  labels:
    name: gwcloud-react-host
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
        name: gwcloud-react-host
  template:
    metadata:
      labels:
        name: gwcloud-react-host
    spec:
      containers:
      - name: gwcloud-react-host
        image: nexus.gwdc.org.au/gwcloud-dev/gwcloud_react_host_static:0.16
        ports:
        - name: http
          containerPort: 8000
        resources: {}
        tty: true
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      imagePullSecrets:
      - name: regcred
...
