---
# NodePort service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud-react-host
  name: gwcloud-react-host
  namespace: gwcloud
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: port-http
    nodePort: 31600
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gwcloud-react-host
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
...

