---
apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-manager
  namespace: demo
  labels:
    app: vault-agent
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-env: "gwcloud/kv/react-host"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "gwcloud/kv/react-host" -}}
           ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: react-host
          type: Opaque
          stringData:
            MYSQL_DATABASE: {{ .Data.data.MYSQL_DATABASE }}
            MYSQL_HOST: {{ .Data.data.MYSQL_HOST }}
            MYSQL_PASSWORD: {{ .Data.data.MYSQL_PASSWORD }}
            MYSQL_ROOT_PASSWORD: {{ .Data.data.MYSQL_ROOT_PASSWORD }}
            MYSQL_USER: {{ .Data.data.MYSQL_USER }}
          ...
          {{- end }}
        vault.hashicorp.com/role: "gwcloud"
      labels:
        app: vault-agent
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      serviceAccountName: gwcloud
      containers:
      - name: app
        image: bitnami/kubectl:1.17.4
        args: [
        "apply","-f","/vault/secrets/env"
        ]
        volumeMounts:
          - mountPath: /.kube
            name: secrets
      nodeSelector:
        kubernetes.io/hostname: node1
      volumes:
        - name: secrets
          hostPath:
            path: /home/ubuntu/.kube
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gwcloud
  namespace: demo
  labels:
    app: vault-agent