apiVersion: v1
kind: Service
metadata:
  labels:
    name: gwcloud_react_host
  name: gwcloud-react-host
  namespace: gwcloud
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: gwcloud_react_host
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}