---
# 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gwcloud-react-host
  namespace: gwcloud
  labels:
    name: gwcloud_react_host
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gwcloud_react_host
    spec:
      containers:
      - name: gwcloud-react-host
        image: nexus.gw-cloud.org/gwcloud-dev/gwcloud_react_host_static:0.1
        ports:
        - name: http
          containerPort: 8000
        resources: {}
        tty: true
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        kubernetes.io/hostname: k8s-3
... 
