---
# Ingress
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: gwc-ing
  namespace: gwcloud
  #annotations:
  # nginx.ingress.kubernetes.io/use-regex: "true"
  # kubernetes.io/ingress.class: "nginx"
  # nginx.ingress.kubernetes.io/rewrite-target: /$1
  #annotations:
  #  kubernetes.io/ingress.class: nginx
  #  nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
  #  nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
spec:
  host: gw-cloud.org
  upstreams:
    - name: gwcloud-auth
      service: gwcloud-auth
      port: 8000
    - name: gwcloud-react-host
      service: gwcloud-react-host
      port: 8000
    - name: gwcloud-job-server-http
      service: gwcloud-job-server
      port: 8000
    - name: gwcloud-job-server-websocket
      service: gwcloud-job-server
      port: 8001
    - name: gwcloud-bilby
      service: gwcloud-bilby
      port: 8000
  routes:
    - path: ~* ^(/auth/static/.*|/auth/graphql|/auth/ligo/|/Shibboleth.sso.*)
      action:
        pass: gwcloud-auth
    - path: ~* ^(/bilby/static/.*|/bilby/graphql)
      action:
        pass: gwcloud-bilby
    - path: ~* ^(/job/ws.*)
      action:
        pass: gwcloud-job-server-websocket
    - path: ~* ^(/job/.*)
      action:
        pass: gwcloud-job-server-http
    - path: / 
      action:
        pass: gwcloud-react-host 
---
