---
# Ingress
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: gwc-ing
  namespace: gwcloud
  #annotations:
  # nginx.ingress.kubernetes.io/use-regex: "true"
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  host: gw-cloud.org
  upstreams:
    - name: gwcloud-auth
      service: gwcloud-auth
      port: 8000
    - name: gwcloud-react-host
      service: gwcloud-react-host
      port: 8000
  routes:
    - path: ~* ^(/auth/static/.*|/auth/graphql|/auth/ligo/)
      action:
        pass: gwcloud-auth
    - path: / 
      action:
        pass: gwcloud-react-host 
---
