---
# Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gwc-ing
  namespace: gwcloud
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    #1kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: gw-cloud.org
    http:
      paths:
      - path: /auth/static/.*
        backend:
          serviceName: gwcloud-auth
          servicePort: 8000
      - path: /auth/graphql
        backend:
          serviceName: gwcloud-auth
          servicePort: 8000
      - path: /auth/ligo/
        backend:
          serviceName: gwcloud-auth
          servicePort: 8000
      - path: /Shibboleth.so
        backend:
          serviceName: gwcloud-auth
          servicePort: 8000
      - path: /
        backend:
          serviceName: gwcloud-react-host
          servicePort: 8000
---
